### ISSUE TITLE
Use a colormap

### ISSUE THREAD

**Issue by flying-sheep** [rbn42/panon#1]
Just cycling through hues isn’t advisable for visualizations due to the wildly fluctuating perceived lightness.

See [here](https://stackoverflow.com/questions/23712207/cyclic-colormap-without-visual-distortions-for-use-in-phase-angle-plots) for a stackoverflow post about why and suggestions what to use (twilight or husl seem to work well).

**Comment by rbn42** [comment]
I can add husl as an option.

**Comment by flying-sheep** [comment]
Awesome, thank you!
