### ISSUE TITLE
Panon uses microphone input instead of speakers / headphones, Manjaro OS

### ISSUE THREAD

**Issue by DjoleDzele** [rbn42/panon#11]
As it says, for some reason on every startup panon only reacts on input from laptop microphone, no matter which backend i choose (tested on all previous versions and also the this one), only sometimes randomly when i manually switch between input devices for microphone (internal / unplugged) and speaker (speakers / headphones) and restart panon in between it sometimes gets to ignore microphone and listen to regular sound output from laptop / headphones, but not really sure what affects its decision? 

I saw there was similar issue posted but im not sure i really understand that whole situation in that post if its same, so to post it as well

**Comment by kupiqu** [comment]
I think it probably is the same issue. It may be a bug somewhere, I think it is most likely in pulseaudio (because the same happens with other backends when using the available testing scripts).

Best configuration I could find so far is to configure ALSA plug-in in pulseaudio settings (pavucontrol) so it captures the Monitor of Internal Stereo Audio (or sth similar, as I'm translating from another language).

If you do that, panon shows the spectrum of output sound (speakers/headphones), while if you select Internal Stereo Audio the spectrum of the input sound is shown (internal/external microphone).

Please give it a try and tell if you see the same behavior.

**Comment by rbn42** [comment]
> because the same happens with other backends when using the available testing scripts

Any way, I added one of the other backends, `python-sounddevice`, as an option in the configuration window, you can try it now, providing you installed the package `python-sounddevice`.

**Comment by rbn42** [comment]
I am using this `default_mic` to record audio, in this [python-soundcard test script ](../blob/master/test/test_python-soundcard.py).
```python
data = default_mic.record(samplerate=48000, numframes=48000)
```
I don't really have a microphone, and this `default_mic` actually record audio from my default speaker. If this script fails in your system, then I guess you need to put a different "mic"/input device into the test script?

**Comment by DjoleDzele** [comment]
test_python-sounddevice and test_QtMultimedia succeed, was unable to test and install correctly python-soundcard

but I tried python-sounddevice now, it doesnt work it seems, it just randomly shows bursts of activity out of nowhere every 10-15 seconds, or it actually works but lags few seconds behind

now i actually tried messing around with pavucontrol program as kupiqu wrote, and it seems to work now, i will post updates if it breaks, I dont even remember having that option there previously for alsa

i went to 
Recording tab --> set ALSA plugin from Monitor of built in audio analog stereo and put it on 100%
Configuration tab --> built in audio --> Analog stereo duplex, and second one (probably does nothing but i dont know) Digital stereo HDMI output(unavailable)

**Comment by rbn42** [comment]
Actually I have little knowledge about this section, about pulseaudio configurations. I myself use the default audio configuration on my own ArchLinux. But may I ask a question? 

> set ALSA plugin from Monitor of built in audio analog stereo and put it on 100%
Configuration tab

Did you mean it was not 100%?

I opened pavucontrol-qt, saw it is 100% already. I think it is 100% by default.
![Screenshot_20191108_211247](https://user-images.githubusercontent.com/8784753/68479129-8cca1980-026c-11ea-9dc4-729bc590be3f.png)

BTW, this is what my configuration tab looks like. My output device is Nvidia HDMI, built in audio is not activated.

![Screenshot_20191108_211129](https://user-images.githubusercontent.com/8784753/68479273-e894a280-026c-11ea-9f6b-623737827759.png)

If the recording program being muted was the only problem, do you think we can add this solution to troubleshooting?

**Comment by DjoleDzele** [comment]
Cant remember exactly if it was on 100% volume previously since i changed everything in it randomly to try it out, In the recording tab photo you posted you dont have the dropdown next to ALSA label, i have 3 options in that dropdown and only when i select "Monitor of built-in audio analog stereo" it works, and also in Configuration tab i must select both things as written previously, otherwise i either have panon working but no sound output, or vice versa if i toggle selections, so both are required for me

**Comment by rbn42** [comment]
> In the recording tab photo you posted you dont have the dropdown next to ALSA label,

Oh, it must be a difference between pavucontrol and pavucontrol-qt. Thought they have same UI.

>  i must select both things as written previously, 

Thank you for this information. I guess it is because panon taking one of them as its input, while you actual audio comes to the other one. I don't know what to do, but this is very helpful.

**Comment by DjoleDzele** [comment]
Yeah, I like panon it's interesting widget to have, glad to help :smiley: If i notice something else i will report :)

**Comment by kupiqu** [comment]
I actually like pavucontrol better than pavucontrol-qt because pavucontrol displays actual sound strength (in a bar underneath), which gives you feedback about what's going on, if it works or not, and so on.

**Comment by rbn42** [comment]
But there is a bar beneath in my pavucontrol-qt screenshot.

**Comment by kupiqu** [comment]
Oops that's right, but it only appears when there is actual sound, that's why I missed because I didn't have any audio going on and my micro was muted :)

Thanks for letting me know, Qt much better ;)

**Comment by rbn42** [comment]
This script can help you add 2 signals together.
```python
from soundcard import pulseaudio as sc
import sys
import os
import numpy as np

SAMPLE_RATE = 44100 # [Hz]
SAMPLE_SIZE = 16 # [bit]
CHANNEL_COUNT = 2
BUFFER_SIZE = 5000 

blocksize=SAMPLE_RATE // 60 

l=sc.all_microphones(                exclude_monitors=False,)

mic0=l[0] # Replace it with the mic you want
mic1=l[1] # Replace it with the mic you want

stream0=mic0.recorder(SAMPLE_RATE,CHANNEL_COUNT,blocksize)
stream0.__enter__()
stream1=mic1.recorder(SAMPLE_RATE,CHANNEL_COUNT,blocksize)
stream1.__enter__()


path = "/tmp/my_program.fifo"
if not os.path.exists(path):
    os.mkfifo(path)
f_fifo=open(path,'wb')
import time
while True:
    data=stream0.record(blocksize)+stream1.record(blocksize)
    data = np.asarray(data * (2**16), dtype='int16').tobytes()
    f_fifo.write(data)

```

After start the script, set fifo path to `/tmp/my_program.fifo`
![Screenshot_20191109_180609](https://user-images.githubusercontent.com/8784753/68526940-2ac8ed00-031c-11ea-9101-20d36e287f80.png)
