### ISSUE TITLE
GetHotNewStuff

### ISSUE THREAD

**Issue by flying-sheep** [rbn42/panon#15]
Should be super easy. Sadly the category isn’t available here, which I think is the reason it doesn’t work: https://store.kde.org/ocs/v1/content/categories

Searching for things in the category does work: https://api.kde-look.org/ocs/v1/content/data?categories=564&tags=panon

`kde/plasmoid/contents/config/panon.knsrc`

```ini
[KNewStuff3]
Name=Panon
ProvidersUrl=https://api.kde-look.org/ocs/providers.xml
Categories=Various KDE Stuff
TagFilter=panon
XdgTargetDir=panon
Uncompress=archive
```

`kde/plasmoid/contents/config/ConfigEffects.qml`

```qml
NewStuff.Button {
    downloadNewWhat: "effects"
    configFile: Utils.get_root() + "/config/panon.knsrc"
}
```

@siyuandong @rvs75 can you help with the category problem?

**Comment by rbn42** [comment]
Sorry, I was finishing the Chinese translation. Now I can focus on this, need to read your post on reddit.com again.

**Comment by flying-sheep** [comment]
Well, all you need is in here. It’s literally that easy.

The only changes apart from those two:

- The KDE store needs to fix its API so GetHotNewStuff finds the packages
- Shaders need to be loaded from `${XDG_DATA_HOME-$HOME/.local/share}/panon` (I think, let’s see where they end up)

I can do a PR once the store thing is fixed

**Comment by rbn42** [comment]
> I can do a PR once the store thing is fixed
You are so nice!

BTW, do you know what was the version of org.kde.newstuff when org.kde.kirigami 2.3 was released? I hope people using org.kde.kirigami 2.3 (like debian 7?) won't have a problem with this org.kde.newstuff.
```qml
import org.kde.newstuff 1.62 as NewStuff
import org.kde.kirigami 2.3 as Kirigami
```

**Comment by rbn42** [comment]
> * Shaders need to be loaded from `${XDG_DATA_HOME-$HOME/.local/share}/panon` (I think, let’s see where they end up)

You can choose either way you consider 

> * Shaders need to be loaded from `${XDG_DATA_HOME-$HOME/.local/share}/panon` (I think, let’s see where they end up)

I can accept either way.

**Comment by flying-sheep** [comment]
> BTW, do you know what was the version of org.kde.newstuff when org.kde.kirigami 2.3 was released? I hope people using org.kde.kirigami 2.3 (like debian 7?) won't have a problem with this org.kde.newstuff.

Good question, sadly no. I think we can look it up by checking any of the `.qml` files in the package, like `/usr/lib/qt/qml/org/kde/newstuff/qml/Button.qml`, because they also contain the import line.

**Comment by rbn42** [comment]
> Good question, sadly I don’t know. I think we can look it up by checking any of the `.qml` files in the package, like `/usr/lib/qt/qml/org/kde/newstuff/qml/Button.qml`, because they also contain the import line.

I will search Debian 7's repo.
