### ISSUE TITLE
Only showing black box after update. 

### ISSUE THREAD

**Issue by NLDev** [rbn42/panon#16]
I've tried to remove the old panon widget and completely reinstall the plugin, but to no avail sadly.
Some tests with PlasmoidViewer were unsuccessful as well: 

![Screenshot_20200121_225528](https://user-images.githubusercontent.com/22935000/72846853-aee70b80-3ca1-11ea-8b93-0c45994ae072.png)

<hr>
<sub>Semi off-topic: Is a german translation needed? I'd be happy to help out on that matter</sub>

**Comment by rbn42** [comment]
Thank you, your report is helpful. But I still need more information. Would you mind to checkout the latest master branch, try to test it again and send me the new logging messages.

> Semi off-topic: Is a german translation needed? I'd be happy to help out on that matter

Yes, that would be appreciated.

**Comment by NLDev** [comment]
> Yes, that would be appreciated.

Alright! Ill start working on it this weekend. 

> try to test it again

Done!

![Screenshot_20200122_080106](https://user-images.githubusercontent.com/22935000/72872468-b8966080-3ced-11ea-908b-c4eba74be910.png)

**Comment by NLDev** [comment]
UPDATE: 
I just checked the ReadMe. Seems like I missed the step 
`git submodule update --init`
Now it shows a black box at first but after changing effect, it seems to work! 
Doesn't explain why the KDE Store version still won't work tho :/

**Comment by rbn42** [comment]
> Doesn't explain why the KDE Store version still won't work tho :/

It seems I forgot to package third party files into the KDE Store verion 0.3.1. Crappy.

> KDE Store Version appears to be working now. I have no idea why

I guess it was because you ran install.sh and installed the git version for KDE panel.

**Comment by rbn42** [comment]
Sorry for your time, it was totally a mistake.

**Comment by NLDev** [comment]
> It seems I forgot to package third party files into the KDE Store verion 0.3.1. Crappy.
> I guess it was because you ran install.sh and installed the git version for KDE panel.

Ah, alright - I see. Thanks for the heads up!

> Sorry for your time, it was totally a mistake.

No need to apologize! Always glad when I can be of some help :) 
Even tho I never coded a KDE widget. But I kinda want to get into it anyway
