### ISSUE TITLE
Panon should tell PulseAudio its name

### ISSUE THREAD

**Issue by flying-sheep** [rbn42/panon#23]
I filed bastibe/SoundCard#81. Once they fixed it, we can adapt the client’s `start` method to set the name:

https://github.com/rbn42/panon/blob/653a7ee73be21cb7ba2f51d24b4ece78e19aea02/panon/backend/source.py#L105-L132

**Comment by rbn42** [comment]
In case you find it too difficult to support it in SoundCard, you can create a patch for `pulseaudio.py` in this repo.
```python
self.context = _pa.pa_context_new(self.mainloop_api, b"panon") 
```
 Just a suggestion.

**Comment by rbn42** [comment]
Thank you for your time and contribution. I just released a new version.

**Comment by flying-sheep** [comment]
And the AUR package is updated!

**Comment by rbn42** [comment]
> And the AUR package is updated

Awesome! Would you mind to add cmake to makedepends to solve #22?

**Comment by rbn42** [comment]
By which I mean
```
- makedepends=('kpackage')
+ makedepends=('kpackage' 'cmake')
```

**Comment by flying-sheep** [comment]
ah sure, done. I also think you don’t need to have a PKGBUILD here, having one copy in the AUR should be sufficient
