### ISSUE TITLE
[BUG] Playing sound casues "network traffic" on the new network monitor plasmoid

### ISSUE THREAD

**Issue by MasterGeekMX** [rbn42/panon#29]
- OS: ArchLinux
 - Version of Plasma Framework: 5.72.0

This is maybe the weirdest bug I have reported so far.
In Plasma 5.19 the system monitoring plasmoids got a revamp. Now all of them are just a plotter of different system stats.
But that causes a particular bug: when both panon and network monitor plasmoids are loaded, if sound is coming out the network plasmoid registers a steady ~ 300KiB/s download/upload traffic, even when there is no actual connection (tried even disconnecting the ethernet cable). If you open other network monitoring tools (like ksysguard) you can see there is no such network traffic at all.

Here is a video I recorded of the issue on a clean user to prove it isn't releated to configs: https://youtu.be/ly8ZyutRec8

**Comment by rbn42** [comment]
This traffic is generated by the lo interface, because audio data is recorded by python, and then sent to qml through websockets.

**Comment by MasterGeekMX** [comment]
Then a "bodge" is to set the sensors to only read the physical network interfaces (enp* and wpl*).
