### ISSUE TITLE
[BUG] {title}

### ISSUE THREAD

**Issue by yuannan** [rbn42/panon#30]
**Desktop (please complete the following information):**
 - OS: Arch Linux 5.8.1-zen1-1-zen
 - Version of Plasma Framework: 5.19.4-1

**Describe the bug**
The default option doesn't work very well. When I select it, it picks the mic up first.

Also after the audio device change it will stay on the old one.

I guess this can be looked as one bug or I'm misunderstanding the settings. What I want is that the visualiser will just visualise whatever is currently playing. The mix setting is a work around but seems like a waste of CPU and I don't like my mic in the mix.

Maybe add a mix what you want setting? or like a tier list of the devices. If this device is not playing, switch to the other one.

**Comment by yuannan** [comment]
> Let me guess, are you describing this situation? When you have picked your microphone in panon, and then plug it out, and then plug it in again, then panon will ignore your microphone?

nope, don't care about the mic at all. I want panon to ignore it in fact.



> > The default option doesn't work very well. When I select it, it picks the mic up first.
> 
> There are two default options, the PortAudio one, and the PulseAudio one. Are you talking about them both? If so, I guess it is highly possible that both upsteam libraries would consider there is some mistakes in your local PulseAudio configuration.

![image](https://user-images.githubusercontent.com/8006928/91063408-ddf1a100-e625-11ea-878a-e1ed205e0740.png)
I'm talking about the default option as in the literally string "default" within the Input device drop down.

> > If this device is not playing, switch to the other one.
> 
> That is possible. I cannot catch the events that an audio device is plugged in or out, but I can repeatedly (like every 3 mins) detect which device is playing when the current one is not playing. It will consume CPU time though.

I understand that, the events are not pushed or pull on your end. I'll be happy to jerry rig my own solution if you can develop a command line interface to this. I can poll the devices streams myself and do it that way.

**Comment by rbn42** [comment]
> I can poll the devices & streams myself and do it that way.

If you can catch the streams, you can write them to a fifo file, like mpd does to /tmp/mpd.fifo. Then panon can read from it.

**Comment by yuannan** [comment]
> > Is there already a text config file I can just edit and reload panon with?
> 
> Sorry, it is embedded within plasma's config file.~You cannot edit and reload it.~ You can use kwriteconfig5 to edit it. But there is no way to reload it.
> 
> > I can poll the devices & streams myself and do it that way.
> 
> If you can catch the streams, you can write them to a fifo file, like mpd does to /tmp/mpd.fifo. Then panon can read the streams from it.
> 
> ![Screenshot_20200825_195642](https://user-images.githubusercontent.com/8784753/91171627-6008c500-e70d-11ea-9c65-56ebd1d79823.png)

seems like the best solution so far, if I manage to develop something not horrific I'll push it back here. Thinking about having a look inside the pulseaudio plasma applet I have and maybe jerrry rig it that way.

Thanks for you help, but yeah, this is not really a fix but more of a really long work around.

**Comment by rbn42** [comment]
Oh, I just notice that you are using an older version of panon. Because it didn't show "Latency/resolution". I am not sure is it what you want, but the newer version has the "Mixing all speakers"(with out mics) option.

Cheers,
