### ISSUE TITLE
[BUG] Constant memory building when placed in Latte Dock

### ISSUE THREAD

**Issue by Nano-Ocelot** [rbn42/panon#32]
- OS: openSUSE Tumbleweed
 - Plasma Framework: 5.75.0
 - Latte-Dock: git-20201009

Memory continues to build when placed in a latte-dock panel. Latte-dock will easily build up to 3GB+ of RAM usage only when panon is active. Memory stops increasing as soon as panon is removed from the panel.

**Comment by rbn42** [comment]
I guess this version of latte-dock has memory leaking problems. 

panon needs to actively draw 60 frames per second, while most of the other plasmoids only display a static image in the most of time. So panon requires much more new memory (by GC) than most of the other plasmoids. So if latte-dock's GC fails, you will find panon's memory leaks more obviously than the other plasmoids.
