### ISSUE TITLE
[BUG] No Pulseaudio Devices

### ISSUE THREAD

**Issue by yuannan** [rbn42/panon#34]
**Desktop (please complete the following information):**
 - OS: Arch Linux 5.9.6-arch1-1
 - Version of Plasma Framework: 5.75.0-1

**Describe the bug**
No pulseaudio devices and can only select "default" but it'll do nothing

FIX:
need the dependency python-cffi in the AUR package

or do pip install cffi

Just want to say thanks for your great work on this visualiser, I've been using it on my main desktop PC and it really spices up task bar. I'm not sure when you made these changes or if I uninstalled something but one day panon just stopped working and I've only recently gotten around to fixing it.

**Comment by rbn42** [comment]
> I've been using it on my main desktop PC and it really spices up task bar.

Thank you.

> I'm not sure when you made these changes or if I uninstalled something but one day panon just stopped working and I've only recently gotten around to fixing it.

Are you sure you didn't uninstall python-cffi unintentionally? Because this package has been required since pulseaudio was introduced as a back-end option 94435c52b62587aa2363bfaa1a124c2a3a94f9d3.

**Comment by rbn42** [comment]
Oh, I see what is the problem. The latest AUR panon build replaced python-cffi with python-soundcard as its dependency. While AUR's python-soundcard build's issue is not fixed yet.
https://aur.archlinux.org/packages/python-soundcard/
![Screenshot_20201110_141417](https://user-images.githubusercontent.com/8784753/98634954-13717500-235f-11eb-9127-b970d8829cc7.png)

@flying-sheep

**Comment by flying-sheep** [comment]
Welp, I’m not the maintainer of that one, but I commented again that they should please fix it.
