### ISSUE TITLE
[BUG] If I restart my pc,the settings for the audio device are changed

### ISSUE THREAD

**Issue by ghost** [rbn42/panon#35]
**Desktop (please complete the following information):**
Manjaro 
Kde Framework 5.76.0
**Describe the bug**
If I restart my pc,I have to re-select which audio device it displays

**Any error message shown in the console**
I can't do this right now,it says that I need the plasma-sdk,but I already have it,I can look later how to fix this.

**Comment by rbn42** [comment]
Could you please upload something similar to this section in your `~/.config/plasma-org.kde.plasma.desktop-appletsrc` or `~/.config/plasmawindowedrc`.

```
[Containments][2][Applets][21]
immutability=1
plugin=panon

[Containments][2][Applets][21][Configuration]
UserBackgroundHints=ShadowBackground

[Containments][2][Applets][21][Configuration][Backend]
bassResolutionLevel=4

[Containments][2][Applets][21][Configuration][Colors]
randomColor=true

[Containments][2][Applets][21][Configuration][ConfigDialog]
DialogHeight=600
DialogWidth=800

[Containments][2][Applets][21][Configuration][Effect]
effectArgTrigger=true
effectArgValues=1,6,#c8000000,0.95,20,12,1.1,0.8,#000000,#000000,#000000,#000000,#000000,#000000
visualEffect=1.rbn42-glowbar
```

In case you cannot find the exact file, you can install the_silver_searcher and search for it by executing

 `cd ~/.config;ag plugin=panon;`

Your configurations are stored in these files. And I hope you can compare them before and after re-selecting and rebooting, to see if any configuration is changed.

**Comment by ghost** [comment]
Sorry,I forgot to answer this issue report,cause it stopped happen some time ago,I don't know what fixed it.
