### ISSUE TITLE
Not working with ALSA and Jack

### ISSUE THREAD

**Issue by lhy0403** [rbn42/panon#4]
I followed the README.md and saw these outputs from the terminal:
```
╭─hall.hexion@Anonymous ~/Projects/panon/kde  ‹master› 
╰─➤ python -m panon.server                   
ALSA lib pcm_dsnoop.c:638:(snd_pcm_dsnoop_open) unable to open slave
ALSA lib pcm_dmix.c:1108:(snd_pcm_dmix_open) unable to open slave
ALSA lib pcm.c:2564:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.rear
ALSA lib pcm.c:2564:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.center_lfe
ALSA lib pcm.c:2564:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.side
ALSA lib pcm_oss.c:377:(_snd_pcm_oss_open) Unknown field port
ALSA lib pcm_oss.c:377:(_snd_pcm_oss_open) Unknown field port
ALSA lib pcm_usb_stream.c:486:(_snd_pcm_usb_stream_open) Invalid type for card
ALSA lib pcm_usb_stream.c:486:(_snd_pcm_usb_stream_open) Invalid type for card
ALSA lib pcm_dmix.c:1108:(snd_pcm_dmix_open) unable to open slave
config {'fps': 30, 'reduceBass': True}
```

Jack is connected, a client shown up and connected to a valid input.
![image](https://user-images.githubusercontent.com/18734999/66132907-63dcb600-e628-11e9-8ca6-de8cbcb51ebb.png)

> The 24667 is the PID for python

However the GUI in my panel left blank (white) and nothing poped out.

 - KDE Plasma latest on ArchLinux
 - Python 3.7
 - Linux 5.3.1

**Comment by rbn42** [comment]
Sorry, I don't have the knowledge to fix this issue. And I guess it is [pyaudio](https://pypi.org/project/PyAudio/)'s problem. Can you try to execute some other pyaudio examples? like this
`
#!/bin/python
"""PyAudio example: Record a few seconds of audio and save to a WAVE file."""

import pyaudio
import wave

CHUNK = 1024
FORMAT = pyaudio.paInt16
CHANNELS = 2
RATE = 44100
RECORD_SECONDS = 5
WAVE_OUTPUT_FILENAME = "output.wav"

p = pyaudio.PyAudio()

stream = p.open(format=FORMAT,
                channels=CHANNELS,
                rate=RATE,
                input=True,
                frames_per_buffer=CHUNK)

print("* recording")

frames = []

for i in range(0, int(RATE / CHUNK * RECORD_SECONDS)):
    data = stream.read(CHUNK)
    frames.append(data)

print("* done recording")

stream.stop_stream()
stream.close()
p.terminate()

wf = wave.open(WAVE_OUTPUT_FILENAME, 'wb')
wf.setnchannels(CHANNELS)
wf.setsampwidth(p.get_sample_size(FORMAT))
wf.setframerate(RATE)
wf.writeframes(b''.join(frames))
wf.close()

`

**Comment by lhy0403** [comment]
Yes, I agree that my sound configuration is very complicated.
I am able to record sounds using your script provided.

![image](https://user-images.githubusercontent.com/18734999/66183844-cecfd080-e6ac-11e9-843c-aceb43dcf5ee.png)

And I can also connect to the WebSocket which Panon Server is listening to. `http://localhost:8765`

**Comment by lhy0403** [comment]
I'll set up a clean KDE install on Debian to test.

**Comment by rbn42** [comment]
> connect to the WebSocket which Panon Server is listening to

Do you get any output then? For example, with connecting the server with this client `example/client.py`, you will get a colorful image

**Comment by lhy0403** [comment]
Well, I think here comes the error:
![image](https://user-images.githubusercontent.com/18734999/66184476-ce383980-e6ae-11e9-811b-3fb8cb5489a0.png)

**Comment by rbn42** [comment]
> It says `KeyError: 'fps'`

Sorry, it is just an error of `client.py`.

**Comment by lhy0403** [comment]
So by adding `await websocket.send('{"fps": 30}')` to the client.py, I'm able to solve that previous issue.
But a new one comes:
Firefox popped up and nothing happens.
And the `img = await websocket.recv()` which recieved in `client.py` is empty.

**Comment by lhy0403** [comment]
It seems to be the `data` in `server.py` is None after tracing back in the source file.
![image](https://user-images.githubusercontent.com/18734999/66185402-ea89a580-e6b1-11e9-8070-c09683660a2d.png)

**Comment by rbn42** [comment]
> And the `img = await websocket.recv()` which recieved in `client.py` is empty.

OK, so it is a server side problem.

Have you ever changed your default audio output device? Have you ever restarted the Panon Server after then if your default audio output device was changed?

**Comment by lhy0403** [comment]
Let me try then.

**Comment by lhy0403** [comment]
There's no change in any devices. I also tested it on a newly installed Ubuntu 19.03 without anything.
The data is None as well.

> It seems to be the `data` in `server.py` is None after tracing back in the source file.
> ![image](https://user-images.githubusercontent.com/18734999/66185402-ea89a580-e6b1-11e9-8070-c09683660a2d.png)

**Comment by rbn42** [comment]
> Well now I think it's an upstream bug.

If this """PyAudio example: Record a few seconds of audio and save to a WAVE file.""" works for you, then I think it is not an upstream bug.

Can you try execute `python -m panon.source` with this new commit 5a14fbad1529d023a9700f8a71a910a3ddd9ac1b

**Comment by lhy0403** [comment]
![image](https://user-images.githubusercontent.com/18734999/66187033-6a197380-e6b6-11e9-9f3c-6b0d1cc8bf19.png)

It just done with nothing.

**Comment by rbn42** [comment]
> It exits with nothing.

It is a new commit 😊

**Comment by lhy0403** [comment]
Oops, sorry.

**Comment by lhy0403** [comment]
It exits with some exceptions:
![image](https://user-images.githubusercontent.com/18734999/66187195-d09e9180-e6b6-11e9-983e-9e67fef31609.png)
`ValueError: zero-size array to reduction operation maximum which has no identity`

**Comment by lhy0403** [comment]
Well the clean install Ubuntu gives 
```
------- blablabla...
ALSA lib pcm_oss.c:377:(_snd_pcm_oss_open) Unknown field port
ALSA lib pcm_usb_stream.c:486:(_snd_pcm_usb_stream_open) Invalid type for card
ALSA lib pcm_usb_stream.c:486:(_snd_pcm_usb_stream_open) Invalid type for card
/home/leroy/panon/panon/source.py:37: DeprecationWarning: The binary mode of fromstring is deprecated, as it behaves surprisingly on unicode inputs. Use frombuffer instead
  data = np.fromstring(data, 'int16')
0 0 0
fail
```

**Comment by rbn42** [comment]
Well, are you sure this """PyAudio example: Record a few seconds of audio and save to a WAVE file.""" really works for you? Did it generate a WAVE file that you can play with, with audio in it? If no, then it is an upstream bug.

And if it is not an upstream bug. Then the only difference between my source.py and this example is the existence of this argument frames_per_buffer=1024. 

Can you add this argument to your source.py and execute `python source.py`.

**Comment by lhy0403** [comment]
> Well, are you sure this """PyAudio example: Record a few seconds of audio and save to a WAVE file.""" really works for you? Did it generate a WAVE file that you can play with, with audio in it? If no, then it is an upstream bug.

Yes it's really producing a `output.wav` for me. I'll test the `source.py` soon

**Comment by rbn42** [comment]
> Yes it's really producing a `output.wav` for me.

And you must play this output.wav, see if your audio was recorded.

**Comment by lhy0403** [comment]
> > Yes it's really producing a `output.wav` for me.
> 
> And you must play this output.wav, see if your audio was recorded.

Yes, I did, I can hear the content and my sound analyzes program says the file is indeed valid.

**Comment by lhy0403** [comment]
Strange, it seems that frames_per_buffer is a has a default value. 
![image](https://user-images.githubusercontent.com/18734999/66190551-dd26e800-e6be-11e9-8078-847ccb3fdfd2.png)
I'll dig further then..

**Comment by rbn42** [comment]
> I'll dig further then..

Thank you, hope you can help fix this source.py. 😊

BTW, on my Archlinux, `python source.py` generates
![2019-10-04-160538_1920x1080_scrot](https://user-images.githubusercontent.com/8784753/66191475-fb8de300-e6c0-11e9-99ec-05c872d9146e.png)

**Comment by lhy0403** [comment]
It's embarrassedly strange on my laptop that it's not working properly......
It might be something wrong with my configuration which made `self.stream.get_read_available()` returns 0
However what's even more strange is... The example code from pyaudio works seamlessly.

**Comment by rbn42** [comment]
> `self.stream.get_read_available()`

This piece of code is not necessary, we can have a workaround.

**Comment by lhy0403** [comment]
![image](https://user-images.githubusercontent.com/18734999/66191973-13199b80-e6c2-11e9-8d1f-90725713da2c.png)

Directly reading from the stream makes it into a infinity loop, it must be some misconfiguration on my side.

**Comment by rbn42** [comment]
I have a solution in mind now.

**Comment by rbn42** [comment]
Can you try f6c74ecd61e50cdf8a1c8d048f0077fe233af509 in a different branch? Does it work?

Now it reads directly from the stream like the pyaudio example. But I guess you may experience lagging if the server started like 10min before the client. 

Or we should force the server keep reading from the stream even there is no client running. I don't know which is better.

**Comment by lhy0403** [comment]
> 10min
Seriously 10 minutes? 😂

**Comment by rbn42** [comment]
uu

> 10min
> Seriously 10 minutes? joy

Like you have a panon server running, and killed latte-dock for 10min, then start another latte-dock.

**Comment by lhy0403** [comment]
It gives an error:
`SIGABORT`

By debugging in pyCharm I saw:
```
Connected to pydev debugger (build 192.6817.19)
ALSA lib pcm_dsnoop.c:638:(snd_pcm_dsnoop_open) unable to open slave
ALSA lib pcm_dmix.c:1108:(snd_pcm_dmix_open) unable to open slave
ALSA lib pcm.c:2564:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.rear
ALSA lib pcm.c:2564:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.center_lfe
ALSA lib pcm.c:2564:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.side
ALSA lib pcm_oss.c:377:(_snd_pcm_oss_open) Unknown field port
ALSA lib pcm_oss.c:377:(_snd_pcm_oss_open) Unknown field port
ALSA lib pcm_usb_stream.c:486:(_snd_pcm_usb_stream_open) Invalid type for card
ALSA lib pcm_usb_stream.c:486:(_snd_pcm_usb_stream_open) Invalid type for card
ALSA lib pcm_dmix.c:1108:(snd_pcm_dmix_open) unable to open slave
free(): invalid next size (normal)
config {'fps': 30}
Original Size: 4096
Loop Mode
A: 16384
```
Note: I inserted some `print` functions in the code.
![image](https://user-images.githubusercontent.com/18734999/66201410-dc4d8080-e6d5-11e9-819c-824a57a23ea2.png)

Is it becoming a low-level Python Bug now?

> BTW: I added another argument that force it connect to my audio device and set my own sample rate to 48000

Seems this line breaks python. What is the proporse of it/?
![image](https://user-images.githubusercontent.com/18734999/66202248-d9538f80-e6d7-11e9-84c0-5e57ee155769.png)

**Comment by rbn42** [comment]
> It gives an error:
> `SIGABORT`

Do you mean you executed `python source.py` or `python -m panon.server` and got this error?

**Comment by lhy0403** [comment]
Well, the latter one, I didn't realize they differences.

**Comment by rbn42** [comment]
>    Seems this line breaks python. What is the proporse of it/?

不好意思,英文不好,这个是python基础,我就用中文解释了.这行代码是从result中截取一个子字符串.负号表示从尾部开始截取,截取长度是max_size,就是确保这个data的最大长度不超过max_size.没有这行代码或许没有影响,因为这里的data应该是比max_size小的(我不确定),所以删掉这一行也不会有差别.

**Comment by lhy0403** [comment]
对不起我以为一开始您是外国人，😂

**Comment by rbn42** [comment]
> 对不起我以为一开始您是外国人，joy

您截图的代码中不是有中文注释吗?我觉得您应该已经知道了才对.

**Comment by lhy0403** [comment]
抱歉抱歉，，那个没有注意到

**Comment by rbn42** [comment]
没,我觉得应该用英文,方便英语使用者参与,因为后面您提及python基础的问题了,所以我想换用中文会比较方便.

**Comment by lhy0403** [comment]
现在的问题是：我好像把简单的问题搞复杂了，因为毕竟我使用那个 pyAudio 是可以正常录到音的，但是现在封装了一下确实是不行了

**Comment by rbn42** [comment]
是命令行直接执行的`python source.py`吗?SIGABORT这种错误,就我的经验来说,一般是出现在debug模式中,而直接执行python反而不会出现这种错误.

**Comment by rbn42** [comment]
> 这个 readlatest 是从音频流里面读取特定大小的音频块吗？

不是,这个是为了确保能读取到音频流中最新的音频块,因为如果是读取到比如10分钟前的音频块显示出来,那就是延迟了.

**Comment by lhy0403** [comment]
> 是命令行直接执行的`python source.py`吗?SIGABORT这种错误,就我的经验来说,一般是出现在debug模式中,而直接执行python反而不会出现这种错误.

我两种都试过了，，，用 `python -m` 的方法是直接提示进程被 Segmentation Fault

![image](https://user-images.githubusercontent.com/18734999/66204512-95638900-e6dd-11e9-9524-ac995cc68352.png)

**Comment by lhy0403** [comment]
我感觉我遇到的问题是，，无论在 if 的什么分支，都都不到音频

**Comment by rbn42** [comment]
> 我两种都试过了，，，用 `python -m` 的方法是直接提示进程被 Segmentation Fault 就很尴尬

这样啊,这种错误的可能性很多,我曾经有过使用部分坏掉的内存的经验,经常出现这种错误,这种可以通过memtest86包检查.感觉有点扯远了.但是这种错误应该认为不是python代码的错误,而是二进制代码或者内存出错了.

**Comment by lhy0403** [comment]
hold on 他好像可以工作了

**Comment by rbn42** [comment]
> 虽然我也不知道我修改了什么

如果您经常遇到这种偶发性错误,编译失败之类的,建议您通过memtest86查个10分钟左右,极可能是硬件导致的.

**Comment by lhy0403** [comment]
我刚刚尝试了一下，关掉 Jack 直接让 PulseAudio 接入 ALSA 是可以用的，这个网上说 python 跟 Jack 还是推荐另外的方法，，

**Comment by lhy0403** [comment]
所以有可能是不兼容，刚刚也看了不是内存问题，把 Jack 的缓冲区调大可以缓解，但是仍然收不到音频块

**Comment by rbn42** [comment]
> 我刚刚尝试了一下，关掉 Jack 直接让 PulseAudio 接入 ALSA 是可以用的，这个网上说 python 跟 Jack 还是推荐另外的方法，，

这个我不懂,我用的是archlinux的默认配置.

> 所以有可能是不兼容，刚刚也看了不是内存问题，把 Jack 的缓冲区调大可以缓解，但是仍然收不到音频块

对我来说无法理解的是,为什么pyaudio example可以而我的source.py不行.明明是一样的代码了

**Comment by lhy0403** [comment]
> 对我来说无法理解的是,为什么pyaudio example可以而我的source.py不行.明明是一样的代码了.它的example中没有提及要关掉 Jack 直接让 PulseAudio 接入 ALSA ,我的source.py中也并没有相关设置.

对这个我也很懵，不知道是什么原因

**Comment by lhy0403** [comment]
因为近期要考试，所以可能需要晚一些时间才能进行彻底的分析

**Comment by lhy0403** [comment]
有一个小小的功能提议
可以添加一下选择音频设备的功能吗？
```
p = pyaudio.PyAudio()
for i in range(p.get_device_count()):
    print(p.get_device_info_by_index(i))
```
open 的时候添加这个参数就好 `input_device_index=blabla`

**Comment by rbn42** [comment]
> 因为近期要考试，所以可能需要晚一些时间才能进行彻底的分析

没关系,如果您希望理清问题的话,我会奉陪,如果您觉得问题太过深入,太废精力,想要放弃,我也可以理解.

**Comment by lhy0403** [comment]
我对panon非常感兴趣，用了这么长时间 Linux 还是第一次见到能在 panel 里面显示 spectrum 的

**Comment by rbn42** [comment]
> 有一个小小的功能提议
> 可以添加一下选择音频设备的功能吗？
> 
> ```
> p = pyaudio.PyAudio()
> for i in range(p.get_device_count()):
>     print(p.get_device_info_by_index(i))
> ```
> 
> open 的时候添加这个参数就好 `input_device_index=blabla`

谢谢,不过我不确定该怎么设计呢,因为进kde store安装这个插件的人,不是每一个都擅长命令行的.所以这种选项应该设计成gui的比较好吧,但是我没有思路该怎么做成gui的选项.

**Comment by lhy0403** [comment]
诶我看你这里是有一个 GUI 设置的
![image](https://user-images.githubusercontent.com/18734999/66209849-e7f77200-e6ea-11e9-9e3b-7d7d34f5925b.png)

所以现在的问题就是如何把获取到的设备列表添加到 UI 的下拉菜单里，
我在用的一个 Plasma-pstate 插件就是通过 shell 获取 CPU 主频
https://github.com/jsalatas/plasma-pstate
但是具体是在哪个文件里实现的，，我确实没有仔细看过

**Comment by rbn42** [comment]
> 我在用的一个 Plasma-pstate 插件就是通过 shell 获取 CPU 主频

是qml吗?很遗憾我不会C++, 如果能和shell交互的话,我倒是希望可以从plasmoid直接启动panon.server,而不是现在这样要求用户手动执行命令.

**Comment by lhy0403** [comment]
> > 我在用的一个 Plasma-pstate 插件就是通过 shell 获取 CPU 主频
> 
> 是qml吗?很遗憾我不会C++, 如果能和shell交互的话,我倒是希望可以从plasmoid直接启动panon.server,而不是现在这样要求用户手动执行命令.

qml 只是一个 GUI 的设计语言吧（我记得好像是的，因为那个 pstate 的项目没有用到c++）
而且 那个项目也是执行了一个 shell ，只需要运行 install.sh 一次，就可以自动调用了
有时间可以一起研究下

**Comment by rbn42** [comment]
>  那个项目也是执行了一个 shell ，只需要运行 install.sh 一次，

我猜测和shell交互的关键代码大概是
```
    PlasmaCore.DataSource {
        id: updater
        engine: 'executable'
```
感觉满意外的,plasma的插件竟然可以放任程序员和shell交互,是不是太过信任社区程序员了.

近日不宜编程呢,我的机场这会似乎全坏了,不能上google搜索文档了,而bing的文档关键词命中率实在太低了.

**Comment by lhy0403** [comment]
😂 近期emm（懂得都懂），过两天就会好了

**Comment by rbn42** [comment]
> 那个项目也是执行了一个 shell ，只需要运行 install.sh 一次

多亏你的提议,现在我可以简化安装和运行步骤了 3f0e424c391ffd040c3bc04143924a677c3d6fbd

**Comment by lhy0403** [comment]
No problem
我这两天试试新版
