### ISSUE TITLE
module "QtWebSockets" is not installed

### ISSUE THREAD

**Issue by andreaemonti** [rbn42/panon#40]
I'm running Manjaro KDE with versions:
Plasma 5.20.5
KDE 5.78.0
Qt 5.15.2

I can't get panon to work: it just displays the following error:
Errore durante il caricamento del file QML: file:///usr/share/plasma/plasmoids/panon/contents/ui/main.qml:11:37: Type Spectrum unavailable
file:///usr/share/plasma/plasmoids/panon/contents/ui/Spectrum.qml:221:5: Type WsConnection unavailable
file:///usr/share/plasma/plasmoids/panon/contents/ui/WsConnection.qml:2:1: module "QtWebSockets" is not installed

I tried both installing panon from aur and installing dependencies with pacman and plasmoid from the plasma UI, but I always get the same result.

**Comment by andreaemonti** [comment]
It seems the python module QtWebSockets is missing, and googling semmes to say taht it should be installed with the package qt5-websockets... but it happens not to be the case

**Comment by rbn42** [comment]
Some people told me, newly installed qt5-websockets may not take effect before you reboot the system.

**Comment by andreaemonti** [comment]
Thanks. It worked. Sorry, I didn't think about it.

**Comment by ghost** [comment]
I've got the same problem but it wasn't fixed after a reboot, weird
