### ISSUE TITLE
[BUG] {panon don't work when reboot. it needs to reset 'visual effects' for  working}

### ISSUE THREAD

**Issue by mongiaK** [rbn42/panon#44]
![image](https://user-images.githubusercontent.com/13835201/107342264-f2a1f280-6afa-11eb-8b4c-6e4a56ac058a.png)

**Comment by rbn42** [comment]
Is this your first installation?

If not, well, I guess your old selected visual effects was modified, renamed, or removed.

**Comment by rbn42** [comment]
1. Is this a screenshot of the configuration before or after resetting 'visual effects'? 

2. Does this issue exist on both Plasma panel and latte-dock?

**Comment by mongiaK** [comment]
> 1. Is this a screenshot of the configuration before or after resetting 'visual effects'?
> 2. Does this issue exist on both Plasma panel and latte-dock?

1. before
2. Plasma panel and latte-dock all in use。

**Comment by mongiaK** [comment]
it was lose ‘--enable-spectrum-data‘ when reboot
![image](https://user-images.githubusercontent.com/13835201/107502292-7202f500-6bd3-11eb-8347-2ba7c88724f9.png)

**Comment by rbn42** [comment]
> it was lose ‘--enable-spectrum-data‘ when reboot

啊，就是因为这个参数缺失导致的错误。不过为什么重启后会丢失这个参数呢？

你会python吗？如果你在/panon/effect/build_shader_source.py的尾部加上
```
json.dump(obj,open('/dev/shm/panon1.log','w'))
json.dump(effect_id,open('/dev/shm/panon2.log','w'))
json.dump(effect_arguments,open('/dev/shm/panon3.log','w'))
```
可以在reboot后，第一次启动panon的时候，把这些变量记录到/dev/shm/panon1.log等文件中，让我们看看哪些变量出问题了。

**Comment by rbn42** [comment]
I made a small modification in the above commit, which may fix this issue. But if not, please 
1. install python-systemd
2. reboot
3. tell me the result of `journalctl -xe | grep panon`

**Comment by PengMengJia** [comment]
> I made a small modification in the above commit, which may fix this issue. But if not, please
> 
> 1. install python-systemd
> 2. reboot
> 3. tell me the result of `journalctl -xe | grep panon`
