### ISSUE TITLE
no audio signal, no empty space

### ISSUE THREAD

**Issue by kupiqu** [rbn42/panon#5]
I wish the widget would not occupy any space when there is no audio signal, so no empty space in the bar when there is no spectrum to show

**Comment by rbn42** [comment]
Good idea, I can add it as option. 

And we need a name for this option, but I am not good at English. So do you know any good name for this option?

**Comment by kupiqu** [comment]
This is how it is done in Window Buttons (https://github.com/psifidotos/applet-window-buttons)

![image](https://user-images.githubusercontent.com/3875196/68031354-e2615d80-fc91-11e9-8251-14df318135e3.png)

You don't need so many options, though but you can choose what you think applies best to panon. With a plus if you could replicate the nice Window Buttons "Slice Out Animation" :)

**Comment by rbn42** [comment]
Like this?
```
Show: Always visible
      Only when audio playing
```

**Comment by kupiqu** [comment]
Sure

**Comment by kupiqu** [comment]
On a second thought, I think it would be more informative if:
```
No audio signal: Preserve space
                 Hide
```
Because it's not really about showing (there is nothing to show anyways), it's about the space that the applet occupies.

**Comment by rbn42** [comment]
I found it is hard resize the plasmoid in runtime. Code below can extend the width to 400, but cannot reduce it to 0.

```
Item{

    Layout.minimumWidth: show_spect? 400:0
    Layout.preferredWidth: Layout.minimumWidth
    Layout.maximumWidth: Layout.minimumWidth
```

**Comment by kupiqu** [comment]
I would suggest taking a look to this functionality in applet-window-buttons:

https://github.com/psifidotos/applet-window-buttons/blob/master/package/contents/ui/main.qml

**Comment by kupiqu** [comment]
I think you may have a typo: need a whitespace before `?` in your code above

**Comment by rbn42** [comment]
I think I find the problem now. It comes from this

```
    Layout.fillWidth:  showMain ? true:false
```

This `fillWidth` property is not honored, after it is changed by `showMain` in Latte-Dock. If this line is replaced by
```
    Layout.fillWidth:  false
```
it works, but then we lose the `fillWidth` option.

**Comment by kupiqu** [comment]
Mmm, I see, that's unfortunate. If there's no easy workaround to this, why not letting the users decide between the two options? Could this be done? 

I actually set a fixed size (I prefer panon to be minimalistic and there's plenty of things in my latte panel already) so I would very much like panon not to occupy space if empty.

**Comment by rbn42** [comment]
> Could this be done?

No problem

**Comment by rbn42** [comment]
Now we can hide the applet when no audio is available. b0509dba81851abd9ecdbad737d85701fe421e54

But there is still a trivia problem. `ConfigGeneral.qml` could not reload the value of `autoHide`  every time you open the configuration window in `Latte-Dock`, while in `plasmoidviewer` it could. Weird to me.

**Comment by rbn42** [comment]
Sorry, I accidentally closed this issue, it was not intended. I don't know how to remove that wrong commit from github.

**Comment by kupiqu** [comment]
It works great, thank you!

**Comment by rbn42** [comment]
OK, then I will release a new version.
