### ISSUE TITLE
[Feature request] Clear/Opacity Changer

### ISSUE THREAD

**Issue by WarpWing** [rbn42/panon#52]
Hello! I was wondering if we could get an opacity changer or a transparent setting?
![image](https://user-images.githubusercontent.com/28925758/109028046-6ad9ed80-768f-11eb-9ee0-7a66c2d5ede4.png)
I would rather not have the darkish box and make it transparent but I'm cool with it either way but it would be nice ^^

**Comment by rbn42** [comment]
#43 This option is already available in Plasma.

**Comment by WarpWing** [comment]
> #43 This option is already available in Plasma.

Sorry about that! I didn't see the option because it's just invisible to me and I didn't know. Thanks for taking the effort to respond to my issue ^^
