### ISSUE TITLE
[Feature request] Widget Placement

### ISSUE THREAD

**Issue by alwzfolwd** [rbn42/panon#54]
Is it possible to add an option to keep above all other windows? Or perhaps configure it as a window so the option is available? 

That would be amazing! Thanks

**Comment by rbn42** [comment]
A widget on the desktop looks like a window, but it is not a window. In KDE, the whole desktop is a window called `plasmashell`. All widgets are attached to this window. 

But there is a way to keep a widget above all other windows: drag the widget into a panel, and keep the panel above all other windows.

You may also be interested in the visualizer [glava](https://github.com/jarcode-foss/glava), which is a standalone window.
