### ISSUE TITLE
[BUG] Does not use specified audio device (Always uses `default`)

### ISSUE THREAD

**Issue by second2050** [rbn42/panon#58]
**Desktop (please complete the following information):**
 - OS: Arch Linux
 - KDE Plasma Version 5.21.5
 - KDE Frameworks Version 5.82.0
 - Using `pipewire-pulse` instead of `pulseaudio`

**Describe the bug**
While using the PulseAudio backend the plasmoid only uses the `default` audio device regardless of what's set in the config window.

**Plasmoid Viewer Log**
[panon.log](https://github.com/rbn42/panon/files/6600118/panon.log)

**Comment by rbn42** [comment]
How did you know it only uses the default audio device? Is it shown in `pgrep -af panon`

**Comment by second2050** [comment]
Okay my bad, I said default audio device because it seemed like it only used the default.

Output of `pgrep` if set to:
"Monitor of Current device":
```
14936 python3 -m panon.backend.client ws://127.0.0.1:34729 --backend=soundcard --device-index=smart --fps=75 --reduce-bass --bass-resolution-level=4 --enable-spectrum-data
```
"Monitor of EMU20K2 [SoundBlaster X-Fi Titanium Series]…":
```
15515 python3 -m panon.backend.client ws://127.0.0.1:34729 --backend=soundcard --device-index=alsa_output.pci-0000_05_00.0.analog-stereo.monitor --fps=75 --reduce-bass --bass-resolution-level=4 --enable-spectrum-data
```
"Monitor of Family 17h (Models 00h-0fh) HD Audio Controller…":
```
15606 python3 -m panon.backend.client ws://127.0.0.1:34729 --backend=soundcard --device-index=alsa_output.pci-0000_0b_00.3.analog-stereo.monitor --fps=75 --reduce-bass --bass-resolution-level=4 --enable-spectrum-data
```
---
In all cases it shows the input of my microphone instead of the what's playing on these devices though.

**Comment by rbn42** [comment]
Please install `python-soundcard`, and try this standalone python script. I want to know could this script record audio data from your other devices, or only from your microphone.
```python
import soundcard as sc
_id="alsa_output.pci-0000_0b_00.3.analog-stereo.monitor"
mic=sc.get_microphone(_id)
stream = mic.recorder(44100,2,44100)
stream.__enter__()
while True:
  data=stream.record(44100)
  if sum(data)==0:
    print('muted',sum(data))
  else:
    print('activated',sum(data))
  ```

**Comment by second2050** [comment]
Output of the script:
```
Traceback (most recent call last):
  File "/home/second2050/rbn42-test.py", line 3, in <module>
    mic=sc.get_microphone(_id)
  File "/usr/lib/python3.9/site-packages/soundcard/pulseaudio.py", line 317, in get_microphone
    return _Microphone(id=_match_soundcard(id, microphones, include_loopback)['id'])
  File "/usr/lib/python3.9/site-packages/soundcard/pulseaudio.py", line 345, in _match_soundcard
    raise IndexError('no soundcard with id {}'.format(id))
IndexError: no soundcard with id alsa_output.pci-0000_0b_00.3.analog-stereo.monitor
```

**Comment by rbn42** [comment]
What soundcard id is available then?
```python
from soundcard import pulseaudio as sc
import json

l = []
for mic in sc.all_microphones(exclude_monitors=False):
    l.append({'id': mic.id, 'name': mic.name})
s = json.dumps(l)
print(s)
```

**Comment by rbn42** [comment]
Oh, sorry, I made a mistake at line 3. please try this script again
```python
import soundcard as sc
_id="alsa_output.pci-0000_0b_00.3.analog-stereo.monitor"
mic=sc.get_microphone(_id,exclude_monitors=False)
stream = mic.recorder(44100,2,44100)
stream.__enter__()
while True:
  data=stream.record(44100)
  if sum(data)==0:
    print('muted',sum(data))
  else:
    print('activated',sum(data))
```

**Comment by second2050** [comment]
Output of the new script was:
```
Traceback (most recent call last):
  File "/home/second2050/rbn42-test.py", line 8, in <module>
    if sum(data)==0:
ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()
```

**Comment by second2050** [comment]
I just did a system update, `pipewire-pulse` in particular got an update, and it's working again as it should.
My guess is that this was a bug introduced by Pipewire and not Panon, therefore I will close this issues for the time being.
