### ISSUE TITLE
[BUG] { module "QtWebSockets" is not installed}

### ISSUE THREAD

**Issue by Asthestarsfalll** [rbn42/panon#62]
file:///home/czh/.local/share/plasma/plasmoids/panon/contents/ui/main.qml:11:37: Type Spectrum unavailable

file:///home/czh/.local/share/plasma/plasmoids/panon/contents/ui/Spectrum.qml:218:5: Type WsConnection unavailable

file:///home/czh/.local/share/plasma/plasmoids/panon/contents/ui/WsConnection.qml:2:1: module "QtWebSockets" is not installed
![image](https://user-images.githubusercontent.com/72954905/126953149-2aa5ca42-8f28-40a4-985f-22431253297f.png)

**Comment by tedneal** [comment]
I was getting the same error while using the Sweet theme on Manjaro. Once I reverted back to a system theme, the newest version of panon ran fine so far.

KDE Plasma Version 5.22.3
KDE Frameworks Version 5.84.0
Qt Version 5.15.2
Kernel Version 5.10.52-1-MANJARO

This error happens on the default repositories and AUR.

**Comment by hugeblank** [comment]
I'm having this issue running the following:
![image](https://user-images.githubusercontent.com/16393543/141690833-feb1e703-b545-461a-9950-4abe0e50ae56.png)

I thought maybe it was a missing dependency so ran:
`sudo apt-get install libqt5websockets5`
and rebooted, but this didn't seem to fix the issue either.

**Comment by Bilalharoon** [comment]
I'm having this bug too.

**Comment by god-damnit** [comment]
anyone got a fix?

**Comment by ghost** [comment]
Any idea how to fix this ?

**Comment by korrykatti** [comment]
Any idea how to fix this ?
