### ISSUE TITLE
No input devices (other than default) after last arch update

### ISSUE THREAD

**Issue by rabfel-hobmet** [rbn42/panon#76]
**Desktop (please complete the following information):**
OS: Arch Linux x86_64 
Kernel: 5.15.7-arch1-1 
Plasma: Plasma 5.23.4

After latest arch update/reboot there is no devices shown on input devices. Have been running without issue for months (no changes)

No errors.

**Comment by YingchangLiu** [comment]
All dependencies of panon have updated yesterday. May be that is the matter.

**Comment by rabfel-hobmet** [comment]
yeah probably...hope it fixes itself. my taskbar looks so boring without panon.

**Comment by bpc1** [comment]
Experienced this as well plus i also found protonup is broken too. It seems like this is a problem with python 3.10 in general since a lot of things are braking that use python: https://bbs.archlinux.org/viewtopic.php?id=272121

Tried downgrading all the dependencies with no luck. I'll just wait for a fix from the python guys i guess.

**Comment by rabfel-hobmet** [comment]
> All dependencies of panon have updated yesterday. May be that is the matter.

any luck fixing it for you?

**Comment by YingchangLiu** [comment]
> 

Not yet.

**Comment by bpc1** [comment]
try this https://github.com/rbn42/panon/issues/78#issuecomment-1003631632

**Comment by entrapta-dev** [comment]
> try this [#78 (comment)](https://github.com/rbn42/panon/issues/78#issuecomment-1003631632)

That does not fix the issue for me as I do not have a `pulseaudio.py` file in my `panon/contents/scripts/soundcard/` folder.

**Comment by rabfel-hobmet** [comment]
i'm unable to find pulseaudio.py even on my computer at all...embarrassing. looks like i'll be waiting still. my desktop looks SO bland right now.

**Comment by bloodyle** [comment]
Manjaro latest update, using pulseaudio, [patched](https://github.com/rbn42/panon/issues/78#issuecomment-1003631632) pulseaudio.py but still not working, showing only 'default' pulseaudio device on backend settings.

**Comment by bloodyle** [comment]
> Manjaro latest update, using pulseaudio, [patched](https://github.com/rbn42/panon/issues/78#issuecomment-1003631632) pulseaudio.py but still not working, showing only 'default' pulseaudio device on backend settings.

Correction - works now after reinstalling the dependecies!

**Comment by cyqsimon** [comment]
See https://github.com/rbn42/panon/issues/78#issuecomment-1007282512 if you cannot find `pulseaudio.py`. TLDR it could be installed globally.

**Comment by hazelshantz** [comment]
this issue still happens on arch. I've been trying to install panon for a while and no sucess. also add support for pipewire as a lot of people is switching to it. 
I've tried installing the dependencies and patching the python file but it still doesn't work. 
I'm running arch with kernel 5.16.2 with kde plasma.5.23.5. tried to install it from the AUR and from kde plasmoids but it doesnt work. same with building it from scratch

**Comment by BruceZhang1993** [comment]
Solution: Re-packaging and reinstall python-soundcard from AUR.

**Comment by rabfel-hobmet** [comment]
> Solution: Re-packaging and reinstall python-soundcard from AUR.

YOU'RE A GENIUS. 

solution: yay -S python-soundcard

and then rebuild from scratch. now it's working. that was so easy.

**Comment by hazelshantz** [comment]
> > Solution: Re-packaging and reinstall python-soundcard from AUR.
> 
> YOU'RE A GENIUS.
> 
> solution: yay -S python-soundcard
> 
> and then rebuild from scratch. now it's working. that was so easy.

yup. its working again now. but consider adding proper pipewire backend support plz. I have to set it to ṕortaudio to make it work with pipewire and use pavucontrol to tell panon which stream is the right one. also, is there a way so make panon more sensitive to the music so effects move more?

**Comment by rabfel-hobmet** [comment]
i spoke too soon. i can now see the different devices but can't get it functioning. going to try a full reinstall and see if that helps.

**Comment by hazelshantz** [comment]
> i spoke too soon. i can now see the different devices but can't get it functioning. going to try a full reinstall and see if that helps.

I had to do a full reinstall of panon to make it work with pipewire. it uses PortAudio as backend. consider adding official pipewire backend support for it.

**Comment by rabfel-hobmet** [comment]
https://github.com/rbn42/panon/issues/78#issuecomment-1007282512
