### ISSUE TITLE
[BUG] Not working even after fixes

### ISSUE THREAD

**Issue by s0m31-hub** [rbn42/panon#90]
made all fixes (pipewire and abc), still not working

**Comment by shadowshard4080** [comment]
Panon doesn't work anymore for me either. I'm on Arch Linux 5.15.44-1-lts and KDE Plasma 5.24.5. Panon used to work about a month ago, now it simply shows the error "Failed to load the visual effect." Changing it in the configuration dialogue does nothing; I've experimented with changing all of the available settings.
![image](https://user-images.githubusercontent.com/90717325/172506842-7780bdc2-7b84-4bd3-b23c-47ceef64bbb0.png)

**Comment by Feefkroete** [comment]
Hi
Did you install all the dependencies from the README?
This fixed it for me - Even if it worked before...
Greetings
Matthi

**Comment by Henshall** [comment]
Got it working - for me I had to upgrade websockets version to 10.x after the abc iterable fix:

pip install --upgrade websockets

got it working on plasma 5.24.2, kde framework 5.92.0, kernel 5.15.0.47-generic, x11

**Comment by s0m31-hub** [comment]
actually noticed that 1 dependency was not installed. Thanks everybody
