### ISSUE TITLE
[BUG] Panon doesn't work on Arch Linux, KDE 5.25.1

### ISSUE THREAD

**Issue by AroLucy** [rbn42/panon#95]
**Desktop (please complete the following information):**
 - OS: ArchLinux
 - Version of Plasma Framework: 5.95.0
 - Version of Plasma: 5.25.1

This message show on the applet once added to the desktop

```
file:///usr/share/plasma/plasmoids/panon/contents/ui/main.qml:11:37: Type Spectrum unavailable

file:///usr/share/plasma/plasmoids/panon/contents/ui/Spectrum.qml:218:5: Type WsConnection unavailable

file:///usr/share/plasma/plasmoids/panon/contents/ui/WsConnection.qml:2:1: module "QtWebSockets" is not installed
```

**Comment by Feefkroete** [comment]
Hi LucyUwl
Do you have QtWebSockets (I don't know the actual package name for Arch) installed?
It's also listed in the README as a dependency so you can just copy the deps for Arch.
Greetings
Matthi

**Comment by AroLucy** [comment]
Thank you, I found that I need `qt5-websockets`and it works now :)
